-- Copyright The OpenTelemetry Authors
-- SPDX-License-Identifier: Apache-2.0

CREATE USER otelu WITH PASSWORD 'otelp';

-- Accounting Service: create a schema
CREATE SCHEMA accounting;
GRANT USAGE ON SCHEMA accounting TO otelu;

-- Accounting Service: create tables
CREATE TABLE accounting."order" (
    order_id TEXT PRIMARY KEY
);

CREATE TABLE accounting.shipping (
    shipping_tracking_id TEXT PRIMARY KEY,
    shipping_cost_currency_code TEXT NOT NULL,
    shipping_cost_units BIGINT NOT NULL,
    shipping_cost_nanos INT NOT NULL,
    street_address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    zip_code TEXT,
    order_id TEXT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES accounting."order"(order_id) ON DELETE CASCADE
);

CREATE TABLE accounting.orderitem (
    item_cost_currency_code TEXT NOT NULL,
    item_cost_units BIGINT NOT NULL,
    item_cost_nanos INT NOT NULL,
    product_id TEXT NOT NULL,
    quantity INT NOT NULL,
    order_id TEXT NOT NULL,
    PRIMARY KEY (order_id, product_id),
    FOREIGN KEY (order_id) REFERENCES accounting."order"(order_id) ON DELETE CASCADE
);

-- Accounting Service: grant permission to schema
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA accounting TO otelu;

-- Product Review Service: create a schema
CREATE SCHEMA reviews;
GRANT USAGE ON SCHEMA reviews TO otelu;

-- Product Review Service: create tables
CREATE TABLE reviews.productreviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(16) NOT NULL,
    username VARCHAR(64) NOT NULL,
    description VARCHAR(1024),
    score NUMERIC(2,1) NOT NULL
);

-- Product Review Service: create index for product_id lookups
CREATE INDEX product_id_index ON reviews.productreviews (product_id);

-- Product Review Service: grant permission to schema
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA reviews TO otelu;

-- Product Review Service:  add product review data
INSERT INTO reviews.productreviews (product_id, username, description, score)
VALUES
    ('OLJCESPC7Z', 'stargazer_mike', 'Great entry-level telescope! Easy to set up and provides clear views of the moon and brighter planets. Highly recommend for new astronomers.', '4.5'),
    ('OLJCESPC7Z', 'nightskylover', 'For the price, this Explorascope delivers excellent performance. I was able to see Jupiter''s moons clearly. A fantastic purchase for casual viewing.', '4.0'),
    ('OLJCESPC7Z', 'beginner_astro', 'A bit tricky to get used to the manual controls, but once you do, it''s very rewarding. Saw the Orion Nebula for the first time! Good value.', '3.5'),
    ('OLJCESPC7Z', 'celestial_explorer', 'Perfect for camping trips. It''s lightweight and portable, making it easy to take anywhere. The views are surprisingly good for its size.', '4.0'),
    ('OLJCESPC7Z', 'telescope_fan', 'Not the most powerful scope, but it''s great for kids and beginners. My children love looking at the moon with it. A solid choice for family fun.', '3.0'),

    ('66VCHSJNUP', 'tech_astro', 'The StarSense app is revolutionary! It made finding celestial objects incredibly easy. This telescope is a game-changer for beginners.', '5.0'),
    ('66VCHSJNUP', 'app_user', 'Amazing technology, the smartphone integration works flawlessly. I''ve never had so much fun exploring the night sky. Worth every penny.', '4.5'),
    ('66VCHSJNUP', 'innovator_john', 'Setup was a breeze, and the tutorials in the app are very helpful. The views are crisp and clear. My only minor gripe is battery drain on the phone.', '4.0'),
    ('66VCHSJNUP', 'clear_skies', 'Finally, a telescope that takes the guesswork out of stargazing. The real-time positioning is incredibly accurate. Highly recommended for anyone new to astronomy.', '5.0'),
    ('66VCHSJNUP', 'gadget_geek', 'Fantastic product, the app truly guides you. It''s like having a personal astronomer with you. The optical quality is also very good.', '4.5'),

    ('1YMWWN1N4O', 'solar_viewer', 'Perfect for solar observations! The Solar Safe filter gives peace of mind. I used it for the last partial eclipse and it was fantastic.', '5.0'),
    ('1YMWWN1N4O', 'eclipse_chaser', 'Compact and easy to carry, this telescope is ideal for eclipse events. The included backpack is a nice touch. Views of the sun are incredibly clear and safe.', '4.5'),
    ('1YMWWN1N4O', 'travel_astro', 'Excellent travel scope for solar viewing. The magnification is much better than binoculars for the sun. A must-have for any solar enthusiast.', '4.0'),
    ('1YMWWN1N4O', 'sun_gazer', 'Very impressed with the safety features and clarity. Sharing the sun with family has never been easier or safer. Great value for a dedicated solar scope.', '5.0'),
    ('1YMWWN1N4O', 'safe_viewer', 'The ISO compliant filter is reassuring. It''s a well-designed product for safe solar observation. Highly recommend for educational purposes too.', '4.5'),

    ('L9ECAV7KIM', 'clean_optics', 'This kit is a lifesaver for all my optics. The brush and wipes work perfectly without leaving any residue. My lenses have never been cleaner.', '5.0'),
    ('L9ECAV7KIM', 'photog_pro', 'Essential for any photographer or telescope owner. It safely removes dust and fingerprints. A high-quality cleaning solution.', '4.5'),
    ('L9ECAV7KIM', 'daily_cleaner', 'I use this on my binoculars, camera lenses, and even my phone screen. It''s very effective and gentle. A versatile cleaning kit.', '4.0'),
    ('L9ECAV7KIM', 'tech_maintenance', 'Great value for money. The different cleaning options cover all needs. Keeps my expensive equipment in pristine condition.', '5.0'),
    ('L9ECAV7KIM', 'sharp_view', 'Works as advertised, my telescope views are much clearer after using this. The fluid and cloth are excellent. Definitely recommend.', '4.5'),

    ('2ZYFJ3GM2N', 'bird_watcher', 'Incredible clarity and brightness, perfect for bird watching. The ED glass really makes a difference. I can spot the subtlest markings.', '5.0'),
    ('2ZYFJ3GM2N', 'nature_lover', 'These binoculars are fantastic for nature observation. The close focus is a huge advantage for viewing nearby wildlife. Very comfortable to hold.', '4.5'),
    ('2ZYFJ3GM2N', 'hiker_guy', 'Lightweight and durable, these are my go-to binoculars for hiking. The wide field of view is excellent. Highly recommend for outdoor enthusiasts.', '4.0'),
    ('2ZYFJ3GM2N', 'stadium_fan', 'Took these to a game and had an amazing view of the action. They perform great in various lighting conditions. A solid all-around binocular.', '4.0'),
    ('2ZYFJ3GM2N', 'outdoor_adventurer', 'Excellent build quality and optical performance. They feel robust and provide sharp images. A great investment for any outdoor activity.', '4.5'),

    ('0PUK6V6EV0', 'astro_photog', 'This imager is a fantastic step up for planetary photography. The color quality is superb. Easy to use with my existing telescope setup.', '5.0'),
    ('0PUK6V6EV0', 'planet_shooter', 'Finally capturing stunning images of Saturn and Jupiter! The NexImage 10 makes it so accessible. Great for beginners in astrophotography.', '4.5'),
    ('0PUK6V6EV0', 'imager_pro', 'Excellent resolution and color rendition for its price point. It''s a perfect solution for those looking to start imaging planets. Highly satisfied.', '4.0'),
    ('0PUK6V6EV0', 'space_artist', 'The detail I can capture with this imager is incredible. It integrates well with various software. A must-have for serious planetary observers.', '5.0'),
    ('0PUK6V6EV0', 'digital_sky', 'A solid choice for getting into solar system imaging. The setup was straightforward. Produces beautiful, vibrant planetary images.', '4.5'),

    ('LS4PSXUNUM', 'night_walker', 'The red light is perfect for preserving night vision during astronomy sessions. The hand warmer is an unexpected bonus. Very practical device.', '5.0'),
    ('LS4PSXUNUM', 'star_party_goer', 'This flashlight is indispensable for star parties. The red mode is gentle on the eyes, and the power bank feature is super handy. Love it!', '4.5'),
    ('LS4PSXUNUM', 'camper_chris', 'Rugged and versatile, this flashlight is great for camping and night walks. The hand warmer function is a game-changer on cold nights. Highly recommend.', '4.5'),
    ('LS4PSXUNUM', 'emergency_kit', 'A fantastic multi-tool for my emergency kit. The red light is useful, and the power bank means I can charge my phone. Great design.', '4.0'),
    ('LS4PSXUNUM', 'astro_accessory', 'Every astronomer needs one of these. The red light is essential, and the hand warmer and power bank make it incredibly useful. A top-tier accessory.', '5.0'),

    ('9SIQT8TOJO', 'deep_sky_master', 'The RASA V2 is a dream come true for deep-sky imaging. The f/2.2 speed drastically cuts down exposure times. My best astrophotography investment yet.', '5.0'),
    ('9SIQT8TOJO', 'pro_astro', 'Unbelievable performance for wide-field astrophotography. The short focal length makes guiding less critical. Produces stunning, detailed images.', '5.0'),
    ('9SIQT8TOJO', 'imaging_guru', 'This OTA is a beast! The fast optics mean more data in less time. If you''re serious about deep-sky imaging, this is the one.', '4.5'),
    ('9SIQT8TOJO', 'advanced_scope', 'Worth every penny for the quality and speed it offers. My images have never been sharper or more vibrant. A truly professional piece of equipment.', '5.0'),
    ('9SIQT8TOJO', 'precision_optics', 'The engineering behind this RASA is exceptional. It''s incredibly efficient for capturing faint objects. A high-end choice for dedicated imagers.', '4.5'),

    ('6E92ZMYYFZ', 'solar_safety', 'Essential for safe solar viewing with my 8-inch telescope. The Velcro straps ensure it stays securely in place. Peace of mind during solar observations.', '5.0'),
    ('6E92ZMYYFZ', 'telescope_upgrade', 'This EclipSmart filter is a perfect addition to my setup. The ISO compliance is crucial. Highly recommend for anyone looking to view the sun safely.', '4.5'),
    ('6E92ZMYYFZ', 'safe_sun_gazer', 'Easy to attach and provides crystal clear, safe views of the sun. The build quality is excellent. A must-have accessory for solar enthusiasts.', '5.0'),
    ('6E92ZMYYFZ', 'filter_fan', 'Works perfectly with my 8-inch scope. No more worries about accidental dislodgement. Great product for protecting your eyes and equipment.', '4.5'),
    ('6E92ZMYYFZ', 'eclipse_ready', 'Bought this for the upcoming eclipse, and it fits perfectly. Tested it out, and the views are fantastic and safe. Very happy with this purchase.', '5.0'),

    ('HQTGWGPNH4', 'history_buff', 'A fascinating glimpse into historical astronomical thought. The content is incredibly insightful. A must-read for anyone interested in the history of science.', '5.0'),
    ('HQTGWGPNH4', 'bookworm_astro', 'Beautifully presented historical document. It''s amazing to see how comets were understood centuries ago. A valuable addition to any astronomy library.', '4.5'),
    ('HQTGWGPNH4', 'ancient_texts', 'Such a unique and intriguing read. The historical context is captivating. It offers a different perspective on celestial events.', '4.0'),
    ('HQTGWGPNH4', 'celestial_history', 'I love historical astronomy, and this book delivers. It''s well-researched and provides a window into past beliefs. Highly recommended for scholars.', '5.0'),
    ('HQTGWGPNH4', 'rare_find', 'A truly special book for enthusiasts of astronomical history. The details about ancient astrologers are very interesting. Great for a deeper understanding.', '4.5');

-- Product Catalog Service: create a schema
CREATE SCHEMA catalog;
GRANT USAGE ON SCHEMA catalog TO otelu;

-- Product Catalog Service: create tables
CREATE TABLE catalog.products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    picture TEXT,
    price_currency_code TEXT NOT NULL,
    price_units BIGINT NOT NULL,
    price_nanos INT NOT NULL,
    categories TEXT
);

-- Product Catalog Service: grant permission to schema
GRANT SELECT ON ALL TABLES IN SCHEMA catalog TO otelu;

-- Product Catalog Service: add product data
INSERT INTO catalog.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories)
VALUES
    ('OLJCESPC7Z', 'National Park Foundation Explorascope', 'The National Park Foundation''s (NPF) Explorascope 60AZ is a manual alt-azimuth, refractor telescope perfect for celestial viewing on the go. The NPF Explorascope 60 can view the planets, moon, star clusters and brighter deep sky objects like the Orion Nebula and Andromeda Galaxy.', 'NationalParkFoundationExplorascope.jpg', 'USD', 101, 960000000, 'telescopes'),
    ('66VCHSJNUP', 'Starsense Explorer Refractor Telescope', 'The first telescope that uses your smartphone to analyze the night sky and calculate its position in real time. StarSense Explorer is ideal for beginners thanks to the app''s user-friendly interface and detailed tutorials. It''s like having your own personal tour guide of the night sky', 'StarsenseExplorer.jpg', 'USD', 349, 950000000, 'telescopes'),
    ('1YMWWN1N4O', 'Eclipsmart Travel Refractor Telescope', 'Dedicated white-light solar scope for the observer on the go. The 50mm refracting solar scope uses Solar Safe, ISO compliant, full-aperture glass filter material to ensure the safest view of solar events.  The kit comes complete with everything you need, including the dedicated travel solar scope, a Solar Safe finderscope, tripod, a high quality 20mm (18x) Kellner eyepiece and a nylon backpack to carry everything in.  This Travel Solar Scope makes it easy to share the Sun as well as partial and total solar eclipses with the whole family and offers much higher magnifications than you would otherwise get using handheld solar viewers or binoculars.', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 129, 950000000, 'telescopes,travel'),
    ('L9ECAV7KIM', 'Lens Cleaning Kit', 'Wipe away dust, dirt, fingerprints and other particles on your lenses to see clearly with the Lens Cleaning Kit. This cleaning kit works on all glass and optical surfaces, including telescopes, binoculars, spotting scopes, monoculars, microscopes, and even your camera lenses, computer screens, and mobile devices.  The kit comes complete with a retractable lens brush to remove dust particles and dirt and two options to clean smudges and fingerprints off of your optics, pre-moistened lens wipes and a bottled lens cleaning fluid with soft cloth.', 'LensCleaningKit.jpg', 'USD', 21, 950000000, 'accessories'),
    ('2ZYFJ3GM2N', 'Roof Binoculars', 'This versatile, all-around binocular is a great choice for the trail, the stadium, the arena, or just about anywhere you want a close-up view of the action without sacrificing brightness or detail. It''s an especially great companion for nature observation and bird watching, with ED glass that helps you spot the subtlest field markings and a close focus of just 6.5 feet.', 'RoofBinoculars.jpg', 'USD', 209, 950000000, 'binoculars'),
    ('0PUK6V6EV0', 'Solar System Color Imager', 'You have your new telescope and have observed Saturn and Jupiter. Now you''re ready to take the next step and start imaging them. But where do you begin? The NexImage 10 Solar System Imager is the perfect solution.', 'SolarSystemColorImager.jpg', 'USD', 175, 0, 'accessories,telescopes'),
    ('LS4PSXUNUM', 'Red Flashlight', 'This 3-in-1 device features a 3-mode red flashlight, a hand warmer, and a portable power bank for recharging your personal electronics on the go. Whether you use it to light the way at an astronomy star party, a night walk, or wildlife research, ThermoTorch 3 Astro Red''s rugged, IPX4-rated design will withstand your everyday activities.', 'RedFlashlight.jpg', 'USD', 57, 80000000, 'accessories,flashlights'),
    ('9SIQT8TOJO', 'Optical Tube Assembly', 'Capturing impressive deep-sky astroimages is easier than ever with Rowe-Ackermann Schmidt Astrograph (RASA) V2, the perfect companion to today''s top DSLR or astronomical CCD cameras. This fast, wide-field f/2.2 system allows for shorter exposure times compared to traditional f/10 astroimaging, without sacrificing resolution. Because shorter sub-exposure times are possible, your equatorial mount won''t need to accurately track over extended periods. The short focal length also lessens equatorial tracking demands. In many cases, autoguiding will not be required.', 'OpticalTubeAssembly.jpg', 'USD', 3599, 0, 'accessories,telescopes,assembly'),
    ('6E92ZMYYFZ', 'Solar Filter', 'Enhance your viewing experience with EclipSmart Solar Filter for 8" telescopes. With two Velcro straps and four self-adhesive Velcro pads for added safety, you can be assured that the solar filter cannot be accidentally knocked off and will provide Solar Safe, ISO compliant viewing.', 'SolarFilter.jpg', 'USD', 69, 950000000, 'accessories,telescopes'),
    ('HQTGWGPNH4', 'The Comet Book', 'A 16th-century treatise on comets, created anonymously in Flanders (now northern France) and now held at the Universitätsbibliothek Kassel. Commonly known as The Comet Book (or Kometenbuch in German), its full title translates as "Comets and their General and Particular Meanings, According to Ptolomeé, Albumasar, Haly, Aliquind and other Astrologers". The image is from https://publicdomainreview.org/collection/the-comet-book, made available by the Universitätsbibliothek Kassel under a CC-BY SA 4.0 license (https://creativecommons.org/licenses/by-sa/4.0/)', 'TheCometBook.jpg', 'USD', 0, 990000000, 'books'),
    ('A1B2C3D4E5', 'Celestron AstroMaster 130EQ', 'The Celestron AstroMaster 130EQ is a powerful reflector telescope with a 130mm aperture that provides bright, clear images of the Moon, planets, and deep-sky objects. The German equatorial mount allows for smooth, precise tracking of celestial objects as they move across the sky.', 'NationalParkFoundationExplorascope.jpg', 'USD', 299, 950000000, 'telescopes'),
    ('F6G7H8I9J0', 'Orion StarBlast 6i IntelliScope', 'The Orion StarBlast 6i IntelliScope reflector telescope features a generous 6-inch aperture and an IntelliScope computerized object locator that helps you find over 14,000 celestial objects with ease. Its tabletop design makes it portable and easy to set up.', 'StarsenseExplorer.jpg', 'USD', 449, 0, 'telescopes'),
    ('K1L2M3N4O5', 'Sky-Watcher ProED 100mm Doublet', 'The Sky-Watcher ProED 100mm Doublet APO Refractor delivers stunning, high-contrast views with minimal chromatic aberration thanks to its extra-low dispersion glass. Perfect for both visual observation and astrophotography.', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 899, 950000000, 'telescopes'),
    ('P6Q7R8S9T0', 'Meade LX90 8-inch ACF', 'The Meade LX90 8-inch ACF (Advanced Coma-Free) telescope features a fast f/10 optical system with Meade''s Ultra-High Transmission Coatings for maximum light throughput. The AudioStar hand controller includes over 30,000 objects in its database.', 'OpticalTubeAssembly.jpg', 'USD', 1599, 0, 'telescopes'),
    ('U1V2W3X4Y5', 'Celestron NexStar 8SE', 'The iconic orange tube of the NexStar 8SE houses a premium 8-inch Schmidt-Cassegrain optical tube on a single fork arm mount with fully computerized GoTo capability. The SkyAlign technology makes setup quick and easy.', 'OpticalTubeAssembly.jpg', 'USD', 1399, 950000000, 'telescopes'),
    ('Z6A7B8C9D0', 'Vixen Optics ED80Sf Refractor', 'The Vixen ED80Sf is a high-quality 80mm ED refractor that produces sharp, color-free images. Its compact size and lightweight design make it an excellent travel scope or guide scope for astrophotography setups.', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 749, 0, 'telescopes,travel'),
    ('E1F2G3H4I5', 'Explore Scientific AR152 Air-Spaced Doublet', 'The AR152 is a 152mm achromatic refractor that delivers impressive views of the Moon, planets, and brighter deep-sky objects. Its large aperture gathers plenty of light for detailed observations at a fraction of the cost of equivalent APO refractors.', 'OpticalTubeAssembly.jpg', 'USD', 699, 950000000, 'telescopes'),
    ('J6K7L8M9N0', 'Celestron CGX Equatorial Mount', 'The Celestron CGX is a heavy-duty computerized equatorial mount designed for mid-sized telescopes and serious astrophotography. It features all-steel construction, a 55-lb payload capacity, and permanent periodic error correction.', 'OpticalTubeAssembly.jpg', 'USD', 1999, 0, 'accessories,mounts'),
    ('O1P2Q3R4S5', 'iOptron SkyGuider Pro', 'The iOptron SkyGuider Pro is a portable camera tracking mount perfect for wide-field astrophotography. It supports up to 11 lbs and features built-in polar alignment scope, making it ideal for capturing the Milky Way and star trails.', 'OpticalTubeAssembly.jpg', 'USD', 458, 0, 'accessories,mounts,travel'),
    ('T6U7V8W9X0', 'ZWO ASI294MC Pro Cooled Camera', 'The ZWO ASI294MC Pro is a cooled color astronomy camera featuring a large 4/3-inch sensor with 11.7 megapixels. The regulated cooling system reduces the sensor temperature up to 35C below ambient for ultra-low noise deep-sky imaging.', 'SolarSystemColorImager.jpg', 'USD', 1099, 0, 'accessories,cameras'),
    ('Y1Z2A3B4C5', 'QHY268C Color Cooled Camera', 'The QHY268C features a back-illuminated 26-megapixel APS-C sensor with extremely low read noise. Its two-stage TEC cooling can reach -35C delta for long-exposure deep-sky imaging with minimal thermal noise.', 'SolarSystemColorImager.jpg', 'USD', 1649, 0, 'accessories,cameras'),
    ('D6E7F8G9H0', 'Baader Planetarium MPCC Mark III', 'The Baader Multi-Purpose Coma Corrector Mark III eliminates coma in fast Newtonian reflectors, producing pinpoint stars across the entire field of view. Essential for astrophotography with reflector telescopes.', 'LensCleaningKit.jpg', 'USD', 249, 950000000, 'accessories'),
    ('I1J2K3L4M5', 'Tele Vue Nagler 13mm Type 6', 'The Tele Vue Nagler 13mm Type 6 eyepiece delivers an immersive 82-degree apparent field of view with razor-sharp optics across the entire field. A legendary eyepiece trusted by serious visual observers worldwide.', 'LensCleaningKit.jpg', 'USD', 290, 0, 'accessories,eyepieces'),
    ('N6O7P8Q9R0', 'Explore Scientific 82-degree 6.5mm', 'This premium eyepiece from the Explore Scientific 82-degree series provides an ultra-wide field of view with edge-to-edge sharpness. Nitrogen-purged and waterproof for durability in all conditions.', 'LensCleaningKit.jpg', 'USD', 169, 950000000, 'accessories,eyepieces'),
    ('S1T2U3V4W5', 'Celestron PowerTank Lithium Pro', 'The PowerTank Lithium Pro is a high-capacity 158.7Wh lithium iron phosphate battery that powers your telescope mount all night long. It features multiple output ports including a cigarette lighter socket and USB ports.', 'RedFlashlight.jpg', 'USD', 199, 950000000, 'accessories,power'),
    ('X6Y7Z8A9B0', 'Thousand Oaks Solar Filter 10-inch', 'Full-aperture glass solar filter for 10-inch telescopes. Made with optical-quality Schott glass coated with nickel-chromium alloy for safe white-light solar viewing. Securely mounts with adjustable thumbscrews.', 'SolarFilter.jpg', 'USD', 89, 950000000, 'accessories,solar'),
    ('C1D2E3F4G5', 'DayStar Quark Chromosphere', 'The DayStar Quark Chromosphere is a hydrogen-alpha solar eyepiece filter that transforms any small refractor into a dedicated solar telescope. See prominences, filaments, and surface detail in stunning contrast.', 'SolarFilter.jpg', 'USD', 1195, 0, 'accessories,solar'),
    ('H6I7J8K9L0', 'Celestron StarPointer Pro', 'The StarPointer Pro is a dual red LED finderscope with adjustable brightness. Its large viewing window makes it easy to sight objects and align your telescope quickly. Compatible with most telescope models.', 'RedFlashlight.jpg', 'USD', 49, 950000000, 'accessories,finders'),
    ('M1N2O3P4Q5', 'Telrad Reflex Finder', 'The Telrad projects concentric red circles onto a glass window, making it intuitive to locate objects using star charts. A classic and beloved finder among amateur astronomers for its simplicity and effectiveness.', 'RedFlashlight.jpg', 'USD', 44, 950000000, 'accessories,finders'),
    ('R6S7T8U9V0', 'Rigel QuikFinder Compact Reflex Sight', 'The Rigel QuikFinder is an ultra-compact reflex sight that projects a bullseye pattern onto the sky. Its low profile and lightweight design make it perfect for any telescope, especially smaller refractors.', 'RedFlashlight.jpg', 'USD', 39, 950000000, 'accessories,finders'),
    ('W1X2Y3Z4A5', 'Astronomik UHC Filter 2-inch', 'The Astronomik UHC (Ultra High Contrast) filter dramatically enhances views of emission nebulae by blocking light pollution while transmitting the critical OIII and H-beta emission lines. A must-have for urban astronomers.', 'SolarFilter.jpg', 'USD', 99, 0, 'accessories,filters'),
    ('B6C7D8E9F0', 'Optolong L-eNhance Dual-Band Filter', 'The L-eNhance is a dual-narrowband filter designed for one-shot color cameras. It isolates H-alpha and OIII emission lines, allowing stunning nebula photography even from light-polluted locations.', 'SolarFilter.jpg', 'USD', 189, 0, 'accessories,filters'),
    ('G1H2I3J4K5', 'Orion SteadyStar Adaptive Optics Guider', 'The SteadyStar uses adaptive optics technology to correct for atmospheric turbulence in real-time, dramatically improving image sharpness during long-exposure astrophotography sessions.', 'SolarSystemColorImager.jpg', 'USD', 2499, 0, 'accessories,cameras'),
    ('L6M7N8O9P0', 'Pegasus Astro FocusCube 3', 'The FocusCube 3 is a precision motorized focuser controller that enables remote and automated focusing. It features a high-resolution stepper motor and temperature sensor for temperature-compensated autofocus.', 'LensCleaningKit.jpg', 'USD', 199, 0, 'accessories,automation'),
    ('Q1R2S3T4U5', 'Primaluce Lab Eagle 4 Pro', 'The Eagle 4 Pro is a complete observatory-in-a-box computer that controls your entire astrophotography setup wirelessly. It features an Intel quad-core processor, multiple USB 3.0 ports, and GPS receiver.', 'RedFlashlight.jpg', 'USD', 2190, 0, 'accessories,automation'),
    ('V6W7X8Y9Z0', 'AstroZap Dew Heater Strips', 'Premium flexible dew heater strips that prevent moisture from forming on your telescope optics during long observation sessions. Available in multiple sizes to fit various telescope apertures and finderscopes.', 'LensCleaningKit.jpg', 'USD', 34, 950000000, 'accessories'),
    ('AA1BB2CC3D', 'Kendrick Dew Controller', 'The Kendrick Dew Controller is a multi-channel dew prevention system that powers and regulates multiple dew heater strips simultaneously. Features adjustable power levels and temperature monitoring.', 'RedFlashlight.jpg', 'USD', 159, 950000000, 'accessories'),
    ('EE4FF5GG6H', 'Bob''s Knobs Collimation Thumbscrews', 'Replace your Newtonian reflector''s factory hex screws with Bob''s Knobs thumbscrews for quick, tool-free collimation in the field. Made from precision-machined stainless steel for smooth, repeatable adjustments.', 'LensCleaningKit.jpg', 'USD', 28, 950000000, 'accessories'),
    ('II7JJ8KK9L', 'Howie Glatter Laser Collimator', 'The Howie Glatter laser collimator is the gold standard for precise Newtonian collimation. Its precision-machined barrel and high-quality laser diode ensure accurate alignment every time.', 'LensCleaningKit.jpg', 'USD', 104, 950000000, 'accessories'),
    ('MM0NN1OO2P', 'Farpoint Carey Focus Mask', 'The Carey Focus Mask (Bahtinov style) slides over your telescope aperture and creates a distinctive diffraction pattern that makes achieving precise focus quick and easy. Essential for astrophotography.', 'LensCleaningKit.jpg', 'USD', 32, 950000000, 'accessories'),
    ('QQ3RR4SS5T', 'Sky-Watcher Star Adventurer Mini', 'The Star Adventurer Mini (SAM) is an ultra-portable tracking mount weighing just 650g. Perfect for lightweight camera-and-lens astrophotography setups while traveling or hiking to dark sky locations.', 'OpticalTubeAssembly.jpg', 'USD', 230, 0, 'accessories,mounts,travel'),
    ('UU6VV7WW8X', 'William Optics RedCat 51', 'The RedCat 51 is a 51mm f/4.9 Petzval astrograph designed specifically for astrophotography. Its quad-element optical design produces a flat, coma-free field ideal for imaging with full-frame cameras.', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 499, 0, 'telescopes,travel'),
    ('YY9ZZ0AB1C', 'Svbony SV503 70ED', 'The SV503 70ED is a budget-friendly 70mm ED doublet refractor that punches well above its price point. Its FPL-53 glass element delivers sharp, color-free views making it an excellent entry into quality refractors.', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 289, 950000000, 'telescopes'),
    ('DE2FG3HI4J', 'Apertura AD8 Dobsonian', 'The Apertura AD8 is a full-featured 8-inch Dobsonian reflector telescope that comes with a premium accessory package including a 2-inch Crayford focuser, laser collimator, and two quality eyepieces.', 'NationalParkFoundationExplorascope.jpg', 'USD', 549, 950000000, 'telescopes'),
    ('KL5MN6OP7Q', 'Orion SkyQuest XT10i IntelliScope', 'The XT10i features a massive 10-inch parabolic mirror that reveals incredible detail in galaxies, nebulae, and star clusters. The IntelliScope object locator helps you navigate to over 14,000 objects.', 'NationalParkFoundationExplorascope.jpg', 'USD', 849, 0, 'telescopes'),
    ('RS8TU9VW0X', 'Celestron Ultima Edge 15mm', 'The Ultima Edge 15mm eyepiece features a flat-field design that eliminates field curvature for sharp stars all the way to the edge. Its 65-degree apparent field of view provides immersive, comfortable viewing.', 'LensCleaningKit.jpg', 'USD', 89, 950000000, 'accessories,eyepieces'),
    ('YZ1AB2CD3E', 'Baader Hyperion 8-24mm Zoom', 'The Baader Hyperion Zoom covers focal lengths from 8mm to 24mm in a single eyepiece, replacing an entire set of eyepieces. Its click-stop zoom mechanism and 68-degree field of view make it incredibly versatile.', 'LensCleaningKit.jpg', 'USD', 259, 0, 'accessories,eyepieces'),
    ('FG4HI5JK6L', 'TeleVue Delos 10mm', 'The TeleVue Delos 10mm delivers a 72-degree apparent field of view with 20mm of eye relief, making it extremely comfortable for extended viewing sessions. Its optical quality is virtually indistinguishable from the legendary Ethos series.', 'LensCleaningKit.jpg', 'USD', 244, 950000000, 'accessories,eyepieces'),
    ('MN7OP8QR9S', 'Nikon Monarch 7 10x42 Binoculars', 'The Monarch 7 features ED glass for superior color correction, a wide 7.0-degree field of view, and a locking diopter for precise focusing. Waterproof and fogproof with a rugged rubber-armored body.', 'RoofBinoculars.jpg', 'USD', 316, 950000000, 'binoculars'),
    ('TU0VW1XY2Z', 'Vortex Diamondback HD 10x42', 'The Diamondback HD 10x42 delivers impressive optical performance with HD glass elements and fully multi-coated lenses. ArmorTek coating protects the exterior, while argon purging ensures fogproof performance.', 'RoofBinoculars.jpg', 'USD', 229, 950000000, 'binoculars'),
    ('AB3CD4EF5G', 'Celestron SkyMaster 15x70', 'The SkyMaster 15x70 binoculars are a favorite among amateur astronomers for their large 70mm objective lenses that gather impressive amounts of light, revealing star clusters, nebulae, and galaxies invisible to smaller optics.', 'RoofBinoculars.jpg', 'USD', 89, 950000000, 'binoculars,astronomy'),
    ('HI6JK7LM8N', 'Fujinon 16x70 FMT-SX Polaris', 'These premium Fujinon binoculars feature individual focus control, EBC multi-coated optics, and a rugged rubber-armored body. Their exceptional optical quality makes them a top choice for astronomical viewing.', 'RoofBinoculars.jpg', 'USD', 549, 0, 'binoculars,astronomy'),
    ('OP9QR0ST1U', 'Oberwerk Ultra 20x80', 'The Oberwerk Ultra 20x80 binoculars feature high-powered magnification and large 80mm objectives for maximum light gathering. Individual focus eyepieces allow precise adjustment for each eye. Ideal for astronomy and long-range terrestrial viewing.', 'RoofBinoculars.jpg', 'USD', 299, 0, 'binoculars,astronomy'),
    ('VW2XY3ZA4B', 'Leica Noctivid 10x42', 'The Leica Noctivid represents the pinnacle of binocular engineering with Schott HT glass, AquaDura hydrophobic lens coating, and incredibly precise mechanical construction. Unmatched optical performance.', 'RoofBinoculars.jpg', 'USD', 2749, 0, 'binoculars'),
    ('CD5EF6GH7I', 'Carson RD-Series 8x42', 'The Carson RD-842 features ED glass, phase-corrected BAK-4 prisms, and fully multi-coated optics in a lightweight, ergonomic body. Exceptional value for birding, nature observation, and casual astronomy.', 'RoofBinoculars.jpg', 'USD', 159, 950000000, 'binoculars'),
    ('JK8LM9NO0P', 'Turn Left at Orion', 'The essential guidebook for amateur astronomers using small telescopes. This highly-rated book provides month-by-month tours of the night sky with detailed finder charts and descriptions of what you will actually see through your eyepiece.', 'TheCometBook.jpg', 'USD', 24, 950000000, 'books'),
    ('QR1ST2UV3W', 'NightWatch: A Practical Guide to Viewing the Universe', 'The definitive stargazing guide featuring star charts, constellation guides, and detailed information on observing techniques. Spiral-bound for easy use in the field with a red-light compatible design.', 'TheCometBook.jpg', 'USD', 29, 950000000, 'books'),
    ('XY4ZA5BC6D', 'The Backyard Astronomer''s Guide', 'Comprehensive reference covering everything from choosing and using telescopes to astrophotography techniques. This extensively revised edition includes the latest equipment recommendations and observing strategies.', 'TheCometBook.jpg', 'USD', 39, 950000000, 'books'),
    ('EF7GH8IJ9K', 'Astronomy with a Home Telescope', 'A beginner-friendly guide to getting the most out of your home telescope. Covers setup, alignment, finding objects, and progressing from simple lunar observations to challenging deep-sky targets.', 'TheCometBook.jpg', 'USD', 15, 950000000, 'books'),
    ('LM0NO1PQ2R', 'Atlas of the Messier Objects', 'Detailed guide to all 110 Messier objects with professional photographs, finder charts, observing notes for various apertures, and historical background. An essential reference for any visual observer.', 'TheCometBook.jpg', 'USD', 49, 950000000, 'books'),
    ('ST3UV4WX5Y', 'Astrophotography for Beginners', 'Step-by-step guide to capturing stunning images of the night sky with minimal equipment. Covers smartphone astrophotography, DSLR techniques, and introduction to dedicated astro cameras and image processing.', 'TheCometBook.jpg', 'USD', 22, 950000000, 'books'),
    ('ZA6BC7DE8F', 'Philip''s Planisphere (Latitude 51.5N)', 'A durable, glow-in-the-dark star chart that shows the visible night sky for any date and time. Simply rotate the overlay to match the current date and time to see which constellations are above the horizon.', 'TheCometBook.jpg', 'USD', 12, 950000000, 'books,accessories'),
    ('GH9IJ0KL1M', 'Celestron SkyPortal WiFi Module', 'Transform your manual telescope into a WiFi-enabled smart scope. The SkyPortal module connects to your smartphone via the free SkyPortal app, providing access to a database of over 120,000 objects and audio tours.', 'RedFlashlight.jpg', 'USD', 89, 0, 'accessories,automation'),
    ('NO2PQ3RS4T', 'Celestron WiFi Telescope Adapter', 'Wirelessly control your Celestron computerized telescope from your iOS or Android device. Stream live video from a connected camera and plan observation sessions using the planetarium view.', 'RedFlashlight.jpg', 'USD', 149, 950000000, 'accessories,automation'),
    ('UV5WX6YZ7A', 'Tele Vue 2x Powermate', 'The Tele Vue 2x Powermate is a telecentric Barlow alternative that maintains the eye relief and field of view of your eyepieces while doubling the magnification. Its 4-element telecentric design produces superior results.', 'LensCleaningKit.jpg', 'USD', 189, 0, 'accessories,eyepieces'),
    ('BC8DE9FG0H', 'Meade Series 5000 2-inch Diagonal', 'The Meade Series 5000 Enhanced Dielectric Diagonal features 99% reflectivity coatings for maximum light throughput. Its precision-machined housing ensures perfect optical alignment for the sharpest views.', 'LensCleaningKit.jpg', 'USD', 199, 0, 'accessories'),
    ('IJ1KL2MN3O', 'William Optics Adjustable Flattener', 'The William Optics Adjustable Flat6A III is a versatile field flattener that works with a wide range of refractors. The adjustable back-focus design makes it easy to achieve a perfectly flat field for astrophotography.', 'LensCleaningKit.jpg', 'USD', 299, 0, 'accessories'),
    ('PQ4RS5TU6V', 'Orion Thin Off-Axis Guider', 'The Thin Off-Axis Guider picks off a small portion of light from the imaging optical path to feed a guide camera, eliminating differential flexure issues common with separate guide scopes. Essential for precise long-exposure imaging.', 'SolarSystemColorImager.jpg', 'USD', 119, 950000000, 'accessories,cameras'),
    ('WX7YZ8AB9C', 'ZWO ASI120MM Mini Guide Camera', 'The ASI120MM Mini is a compact monochrome guide camera perfect for autoguiding. Its small size, low weight, and excellent sensitivity make it the ideal companion for any autoguiding setup using PHD2 or similar software.', 'SolarSystemColorImager.jpg', 'USD', 149, 0, 'accessories,cameras'),
    ('DE0FG1HI2J', 'Pegasus Astro Pocket Powerbox', 'The Pocket Powerbox is a compact power distribution hub for your astrophotography rig. It features multiple 12V outputs, a dew heater controller, USB hub, and environmental sensors, all manageable via ASCOM or INDI drivers.', 'RedFlashlight.jpg', 'USD', 249, 0, 'accessories,automation,power'),
    ('KL3MN4OP5Q', 'Astro-Physics Mach1GTO Mount', 'The Astro-Physics Mach1GTO is a premium German equatorial mount renowned for its exceptional tracking accuracy and smooth motion. With a 35-lb instrument capacity, it handles mid-sized imaging rigs with ease.', 'OpticalTubeAssembly.jpg', 'USD', 5295, 0, 'accessories,mounts'),
    ('RS6TU7VW8X', 'Losmandy G11 Gemini 2 Mount', 'The Losmandy G11 is a legendary German equatorial mount trusted by astrophotographers worldwide. The Gemini 2 GoTo system provides accurate pointing and tracking for payloads up to 60 lbs.', 'OpticalTubeAssembly.jpg', 'USD', 3795, 0, 'accessories,mounts'),
    ('YZ9AB0CD1E', 'Sky-Watcher EQ6-R Pro', 'The EQ6-R Pro is a belt-driven computerized equatorial mount with a 44-lb payload capacity. Its SynScan GoTo system includes a database of over 42,000 objects, and the belt drive system ensures smooth, backlash-free tracking.', 'OpticalTubeAssembly.jpg', 'USD', 1550, 0, 'accessories,mounts'),
    ('FG2HI3JK4L', 'Starlight Xpress Trius SX-694 Mono', 'The Trius SX-694 is a cooled monochrome CCD camera featuring Sony''s ICX694 sensor with 6 megapixels and very low read noise. Regulated cooling to -40C delta makes it ideal for narrowband deep-sky imaging.', 'SolarSystemColorImager.jpg', 'USD', 1795, 0, 'accessories,cameras'),
    ('MN5OP6QR7S', 'Player One Poseidon-C Pro', 'The Poseidon-C Pro features a cooled IMX571 APS-C color sensor with back-illuminated technology for exceptional quantum efficiency. Its 26-megapixel resolution and low noise make it a top choice for one-shot color deep-sky imaging.', 'SolarSystemColorImager.jpg', 'USD', 1299, 0, 'accessories,cameras'),
    ('TU8VW9XY0Z', 'Chroma H-alpha 3nm Filter 2-inch', 'The Chroma H-alpha 3nm narrowband filter is a professional-grade interference filter that isolates the hydrogen-alpha emission line with extremely high transmission and narrow bandpass. Made in the USA.', 'SolarFilter.jpg', 'USD', 449, 0, 'accessories,filters'),
    ('AB1CD2EF3G', 'Astrodon OIII 3nm Filter 2-inch', 'The Astrodon OIII 3nm narrowband filter provides exceptional isolation of the doubly-ionized oxygen emission lines. Combined with H-alpha, it enables stunning bi-color and narrowband palette imaging from urban locations.', 'SolarFilter.jpg', 'USD', 399, 0, 'accessories,filters'),
    ('HI4JK5LM6N', 'Astronomik CLS-CCD Filter 2-inch', 'The CLS-CCD filter is designed to enhance contrast for CCD and CMOS cameras under light-polluted skies. It blocks common sources of artificial light while preserving the full spectrum of deep-sky object emissions.', 'SolarFilter.jpg', 'USD', 119, 0, 'accessories,filters'),
    ('OP7QR8ST9U', 'Orion 1.25-inch Filter Set', 'This four-filter set includes #25A Red, #12 Yellow, #56 Green, and #80A Blue filters for enhancing planetary and lunar observations. Each glass filter threads into standard 1.25-inch eyepieces for easy attachment.', 'SolarFilter.jpg', 'USD', 54, 950000000, 'accessories,filters'),
    ('VW0XY1ZA2B', 'Orion Observer 70mm Altazimuth Refractor', 'A great starter telescope for young aspiring astronomers. The 70mm aperture provides clear views of the Moon''s craters and Saturn''s rings. Includes two eyepieces and an EZ Finder II reflex sight for easy object location.', 'NationalParkFoundationExplorascope.jpg', 'USD', 109, 950000000, 'telescopes'),
    ('CD3EF4GH5I', 'Celestron FirstScope', 'The Celestron FirstScope is a tabletop Dobsonian telescope perfect for kids and beginners. Its 76mm aperture reveals lunar craters, Jupiter''s moons, and Saturn''s rings. Named after notable astronomers engraved on its base.', 'NationalParkFoundationExplorascope.jpg', 'USD', 54, 950000000, 'telescopes'),
    ('JK6LM7NO8P', 'Meade StarNavigator NG 114mm Reflector', 'The StarNavigator NG 114mm is an excellent mid-range reflector with a fully computerized AudioStar GoTo controller. Features a 114mm parabolic primary mirror and includes two Modified Achromatic eyepieces.', 'NationalParkFoundationExplorascope.jpg', 'USD', 349, 0, 'telescopes'),
    ('QR9ST0UV1W', 'Sky-Watcher Heritage 150P FlexTube', 'The Heritage 150P is a collapsible Dobsonian with a 150mm parabolic mirror that folds down for easy transport. Its unique FlexTube design makes it one of the most portable 6-inch telescopes available.', 'NationalParkFoundationExplorascope.jpg', 'USD', 289, 950000000, 'telescopes,travel'),
    ('XY2ZA3BC4D', 'Orion SpaceProbe 130ST EQ Reflector', 'The SpaceProbe 130ST features a short-tube 130mm reflector on a stable equatorial mount. Its fast f/5 focal ratio produces wide-field views of deep-sky objects while remaining compact enough for easy transport.', 'NationalParkFoundationExplorascope.jpg', 'USD', 299, 950000000, 'telescopes'),
    ('EF5GH6IJ7K', 'Celestron Astro Fi 102mm Maksutov', 'The Astro Fi 102 is a WiFi-enabled Maksutov-Cassegrain telescope controlled entirely from your smartphone or tablet. Its compact 102mm design delivers high-contrast planetary views with computerized GoTo convenience.', 'StarsenseExplorer.jpg', 'USD', 449, 950000000, 'telescopes'),
    ('LM8NO9PQ0R', 'Levenhuk Skyline PLUS 120S Telescope', 'The Skyline PLUS 120S is a large-aperture short-tube reflector ideal for beginners wanting to explore deep-sky objects. Its stable equatorial mount and included accessories make it ready for immediate use.', 'NationalParkFoundationExplorascope.jpg', 'USD', 259, 0, 'telescopes'),
    ('ST1UV2WX3Y', 'Unistellar eQuinox 2', 'The eQuinox 2 is a smart digital telescope that uses Enhanced Vision technology to reveal deep-sky objects in vivid color in real-time. Fully automated with GPS alignment and a companion app for effortless stargazing.', 'StarsenseExplorer.jpg', 'USD', 2499, 0, 'telescopes,smart'),
    ('ZA4BC5DE6F', 'Vaonis Vespera', 'The Vaonis Vespera is an observation station that combines a 50mm quadruplet refractor with a Sony IMX462 sensor. It autonomously captures and stacks images of celestial objects, displaying them on your device in real-time.', 'StarsenseExplorer.jpg', 'USD', 1499, 0, 'telescopes,smart'),
    ('GH7IJ8KL9M', 'ZWO Seestar S50', 'The Seestar S50 is an all-in-one smart telescope featuring a 50mm APO refractor, integrated camera, and electronic tripod. One-tap GoTo, autofocus, and live stacking make astrophotography accessible to everyone.', 'StarsenseExplorer.jpg', 'USD', 499, 0, 'telescopes,smart'),
    ('NO0PQ1RS2T', 'Celestron Origin Intelligent Home Observatory', 'The Celestron Origin is a 6-inch Rowe-Ackermann Schmidt Astrograph with built-in camera and EdgeHD optics. It captures, processes, and stacks images autonomously, delivering stunning deep-sky images to your device.', 'StarsenseExplorer.jpg', 'USD', 3999, 0, 'telescopes,smart'),
    ('UV3WX4YZ5A', 'Bresser Messier AR-102/1000 EXOS-2', 'A classic 102mm achromatic refractor on the sturdy EXOS-2 equatorial mount. This combination provides excellent planetary and lunar views with precise manual tracking via the mount''s flexible slow-motion controls.', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 599, 0, 'telescopes'),
    ('BC6DE7FG8H', 'Omegon Pro APO 72/400 Quintuplet', 'The Omegon Pro APO 72/400 is a compact quintuplet astrograph with a perfectly flat, well-corrected field. Designed for portable wide-field astrophotography with exceptional sharpness across full-frame sensors.', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 649, 0, 'telescopes,travel'),
    ('IJ9KL0MN1O', 'Meade Polaris 130EQ Reflector', 'The Polaris 130EQ is a 130mm Newtonian reflector on a German equatorial mount. It comes with three eyepieces, a 2x Barlow lens, and a red-dot viewfinder, making it a complete package for beginners.', 'NationalParkFoundationExplorascope.jpg', 'USD', 249, 950000000, 'telescopes'),
    ('PQ2RS3TU4V', 'Celestron AstroMaster 114EQ', 'A popular entry-level reflector with a 114mm Newtonian optical tube on a manual German equatorial mount. The AstroMaster 114EQ reveals Saturn''s rings, Jupiter''s cloud bands, and countless deep-sky treasures.', 'NationalParkFoundationExplorascope.jpg', 'USD', 219, 950000000, 'telescopes'),
    ('WX5YZ6AB7C', 'Orion StarMax 90mm Tabletop Maksutov', 'The StarMax 90 is a compact Maksutov-Cassegrain telescope perfect for planetary viewing from a tabletop. Its 90mm aperture and long 1250mm focal length deliver high-contrast, detailed views of the Moon and planets.', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 199, 0, 'telescopes,travel'),
    ('DE8FG9HI0J', 'Coronado PST Personal Solar Telescope', 'The Coronado PST is a dedicated hydrogen-alpha solar telescope that reveals prominences, filaments, and active regions on the Sun''s surface. Its 40mm aperture and built-in H-alpha filter make solar viewing safe and easy.', 'SolarFilter.jpg', 'USD', 699, 0, 'telescopes,solar'),
    ('KL1MN2OP3Q', 'Lunt LS60THa Solar Telescope', 'The Lunt LS60THa is a 60mm hydrogen-alpha solar telescope with a pressure-tuned etalon for precise H-alpha bandpass adjustment. Reveals stunning solar surface detail, prominences, and filaments in exquisite contrast.', 'SolarFilter.jpg', 'USD', 1295, 0, 'telescopes,solar'),
    ('RS4TU5VW6X', 'Explore Scientific 127mm ED APO', 'The ES 127mm ED APO is a premium 5-inch air-spaced triplet refractor with FPL-53 glass. It delivers virtually color-free, razor-sharp images for both demanding visual observers and astrophotographers.', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 2699, 0, 'telescopes'),
    ('YZ7AB8CD9E', 'Takahashi TSA-120 Refractor', 'The Takahashi TSA-120 is a legendary 120mm triplet APO refractor with a modified triplet design using Super ED glass. Renowned for its superb optics and mechanical precision. A pinnacle of Japanese optical engineering.', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 4980, 0, 'telescopes'),
    ('FG0HI1JK2L', 'Celestron Advanced VX 8 EdgeHD', 'The Advanced VX 8 EdgeHD combines Celestron''s aplanatic EdgeHD optics with the capable Advanced VX computerized mount. The system delivers coma-free images across the entire field, ideal for both visual and imaging use.', 'OpticalTubeAssembly.jpg', 'USD', 2599, 0, 'telescopes'),
    ('MN3OP4QR5S', 'Meade LX200 12-inch ACF', 'The Meade LX200 12-inch ACF is a premium fork-mounted Schmidt-Cassegrain with GPS alignment and over 145,000 objects in its database. The 12-inch aperture reveals stunning detail in galaxies and planetary nebulae.', 'OpticalTubeAssembly.jpg', 'USD', 4499, 0, 'telescopes'),
    ('TU6VW7XY8Z', 'Obsession 18-inch UC Dobsonian', 'The Obsession 18-inch Ultra Compact is a premium truss-tube Dobsonian that breaks down for transport. Its massive 18-inch mirror gathers enormous amounts of light, revealing incredibly faint deep-sky objects in breathtaking detail.', 'NationalParkFoundationExplorascope.jpg', 'USD', 6495, 0, 'telescopes'),
    ('AB9CD0EF1G', 'Sky-Watcher Quattro 200P Imaging Newtonian', 'The Quattro 200P is a fast f/4 imaging Newtonian with a dual-speed Crayford focuser and integrated corrector lens adapter. Designed specifically for astrophotography, it delivers wide-field images with pinpoint stars.', 'OpticalTubeAssembly.jpg', 'USD', 599, 0, 'telescopes'),
    ('HI2JK3LM4N', 'Vixen A80Mf Refractor', 'The Vixen A80Mf is a reliable 80mm achromatic refractor built with Vixen''s renowned mechanical quality. Its smooth rack-and-pinion focuser and multi-coated optics deliver pleasing views of the Moon, planets, and double stars.', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 329, 0, 'telescopes'),
    ('OP5QR6ST7U', 'Celestron CGEM II 925 EdgeHD', 'The CGEM II 925 EdgeHD pairs a 9.25-inch aplanatic Schmidt-Cassegrain with the robust CGEM II computerized equatorial mount. This system is a serious astrophotography platform capable of stunning deep-sky images.', 'OpticalTubeAssembly.jpg', 'USD', 3999, 0, 'telescopes'),
    ('VW8XY9ZA0B', 'Astro-Tech AT130EDT Triplet Refractor', 'The AT130EDT is a 130mm f/7 triplet APO refractor with FPL-53 glass and a 3-inch Crayford focuser. It delivers excellent color correction and sharpness for both visual observation and astrophotography.', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 1699, 0, 'telescopes');
